### ISSUE TITLE
Adding your changes to main OpenModManager repo

### ISSUE THREAD

**Issue by mcu8** [jlintgod1/OpenModManager#1]
Hi, I just noticed that you forked my code and made some nice changes!
Can I add them into my main branch? Of course I'll add you in the credits :)

Or we can git merge changes from this repository with mine, but that would probably require a lot more work.

**Comment by jlintgod1** [comment]
Hey, just noticed your comment(because GitHub didn't notify me lol), but you can integrate my changes! There's some details about changes you probably shouldn't grab though:

- The Hat.ovh browser: It's not finished, and I'm not exactly sure if it's something people would want. After all, there's a functioning web browser right next to them that they can use for downloading scripts.
- The screenshot/preview images uploader: I tried it out with my mod Improved Hookshot Visuals, and while it does work and allow for quickly uploading high quality screenshots directly from the game, I noticed them randomly disappear on the workshop page. It could use some extra testing before it's formally introduced.
- Removing the updater: You have this infrastructure lol
- All the jlintgod (inside) jokes: Uhh yeah you don't need a random jlintgod the Spider in the about window or random title text mentioning random jlintgod jokes lol. Mustard.

Anyway, thanks for taking note of all of this! I never really mentioned this fork to anybody at all, and I think it's good to actually put it towards something.

-Jlintgod

P.S. There's a few more changes I haven't committed yet, but I will soon(by soon, I mean five minutes lol)
